version: 2.1
jobs:
  build:
    docker:
      - image: debian:latest # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: echo "hello world" # run the `echo` command
      - run:
          command: |
            whoami
            pwd
      - run:
          command: |
            apt update

